/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.vendedorCRUD;
import Modelo.Vendedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class FORM_agregarVend extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FORM_agregarVend.class.getName());

    /**
     * Creates new form FORM_agregarVend
     */
    public FORM_agregarVend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_rut_dosPrimeros = new javax.swing.JTextField();
        jtxt_rut_dv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpw_pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxt_nombre = new javax.swing.JTextField();
        jtxt_snombre = new javax.swing.JTextField();
        jtxt_amaterno = new javax.swing.JTextField();
        jtxt_apaterno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtxt_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jpw_confirmar = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jrbtn_si = new javax.swing.JRadioButton();
        jrbtn_no = new javax.swing.JRadioButton();
        jbtn_volv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setText("RUT: ");

        jtxt_rut_dv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_rut_dvActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("-");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Contraseña:");

        jpw_pass.setText("jPasswordField1");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nombre: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Segundo nombre :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Apellido Paterno: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Apellido Materno: ");

        jtxt_amaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_amaternoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Username: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Confirmar");

        jpw_confirmar.setText("jPasswordField1");
        jpw_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpw_confirmarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("contraseña");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Administrador: ");

        jrbtn_si.setText("Si");

        jrbtn_no.setText("No");

        jbtn_volv.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_volv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtn_volv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        jbtn_volv.setText("Volver");
        jbtn_volv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(218, 218, 218))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxt_user, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxt_amaterno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxt_apaterno)
                                .addComponent(jtxt_snombre)
                                .addComponent(jtxt_nombre)
                                .addComponent(jpw_confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                                .addComponent(jpw_pass, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxt_rut_dosPrimeros, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_rut_dv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(jbtn_volv, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(20, 20, 20)
                        .addComponent(jrbtn_no, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbtn_si, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxt_rut_dosPrimeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_rut_dv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jbtn_volv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jpw_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jpw_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxt_snombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtxt_apaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jtxt_amaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jrbtn_si)
                    .addComponent(jrbtn_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_rut_dvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_rut_dvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_rut_dvActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean admin = false;
        int run_vendedor = 0;
        char[] passwordArray = this.jpw_pass.getPassword();
        String passw = new String(passwordArray);
        String apellidoM_vendedor = this.jtxt_amaterno.getText();
        String apellidoP_Vendedor = this.jtxt_apaterno.getText();
        String username = this.jtxt_user.getText();
        String dv_rut_vendedor = this.jtxt_rut_dv.getText();
        String nombre_vendedor = this.jtxt_nombre.getText();
        String segundo_nombre_vendedor = this.jtxt_snombre.getText();
        char[] passwordArray1 = this.jpw_confirmar.getPassword();
        String passw1 = new String(passwordArray1);
        String rut = this.jtxt_rut_dosPrimeros.getText();
        vendedorCRUD vendC = new vendedorCRUD();
        if (!passw1.equals(passw)) {
            JOptionPane.showMessageDialog(this, "Contraseñas deben coincidir", "Error de contraseña", 2);
            throw new IllegalArgumentException("Contraseña no coincide");
        }
        
        if (this.jrbtn_si.isSelected()){
            admin = true;
        }

        if (nombre_vendedor.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre", "ERROR", 2);
            this.jtxt_nombre.requestFocus();
            throw new IllegalArgumentException("No ingresa nombre");
        }

        if (username.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de usuario", "Error de ingreso", 2);
            this.jtxt_user.requestFocus();
            throw new IllegalArgumentException("No ingresa username");
        }

        if (dv_rut_vendedor.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un digito verificador en el rut", "Error de ingreso", 2);
            this.jtxt_rut_dv.requestFocus();
            throw new IllegalArgumentException("No ingresa digito verificador");
        }
        if (segundo_nombre_vendedor.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un segundo nombre", "Error de ingreso", 2);
            this.jtxt_snombre.requestFocus();
            throw new IllegalArgumentException("No ingresa segundo nombre");
        }

        if (apellidoM_vendedor.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un apellido materno", "Error de ingreso", 2);
            this.jtxt_apaterno.requestFocus();
            throw new IllegalArgumentException("No ingresa apellido materno");
        }

        if (rut.length() > 12) {
            JOptionPane.showMessageDialog(this, "La longitud del rut debe ser menor o igual a 12", "Error de ingreso", 2);
            this.jtxt_rut_dosPrimeros.requestFocus();
            throw new IllegalArgumentException("RUT 12");
        }
        if (apellidoP_Vendedor.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un apellido paterno", "Error de ingreso", 2);
            throw new IllegalArgumentException("no ingreso nada");
        }
        
        if (this.uservend(username)){
            JOptionPane.showMessageDialog(this, "El username debe ser unico", "Error de ingreso", 2);
            this.jtxt_user.requestFocus();
            this.jtxt_user.setText("");
            throw new IllegalArgumentException("Usuario repetido");
        }
        try {
            run_vendedor = Integer.parseInt(this.jtxt_rut_dosPrimeros.getText());
            List<Vendedor> lista = new ArrayList<>();
            lista = vendC.listarVendedores();
            for (Vendedor vendedor : lista) {
                if (run_vendedor == vendedor.getRun_vendedor()) {
                    JOptionPane.showMessageDialog(this, "Ya existe un usuario con este rut", "Error de ingreso", 2);
                    throw new IllegalArgumentException("rut ya existe");
                    
                }
                
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El rut debe ser numérico", "Ingreso RUT", 2);
            this.jtxt_rut_dosPrimeros.requestFocus();
            throw new IllegalArgumentException("rut debe ser numerico");
        }
        
       


        Vendedor vendedor = new Vendedor(run_vendedor, dv_rut_vendedor, username, nombre_vendedor, segundo_nombre_vendedor, apellidoP_Vendedor, apellidoM_vendedor, admin);
        vendedorCRUD vendc = new vendedorCRUD();

        if (vendc.agregarVendedor(vendedor, passw)) {

            JOptionPane.showMessageDialog(this, "Se agregó el vendedor", "Ingreso Vendedor", 1);

        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar Vendedor", "Vendedor no Ingresado", 2);

        }
        


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jpw_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpw_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpw_confirmarActionPerformed

    private void jtxt_amaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_amaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_amaternoActionPerformed

    private void jbtn_volvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volvActionPerformed
        FORM_admin ad = new FORM_admin();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_volvActionPerformed


    
    private boolean uservend (String username){
        vendedorCRUD vendC = new vendedorCRUD();
        List<Vendedor> vend = new ArrayList<>();
        vend = vendC.listarVendedores();
        boolean flag = false;
        
        for (Vendedor vendedor : vend) {
            
            if (username.equals(vendedor.getUsername())) {
                flag = true;
                
            }
            
        }
        return flag;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new FORM_agregarVend().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_volv;
    private javax.swing.JPasswordField jpw_confirmar;
    private javax.swing.JPasswordField jpw_pass;
    private javax.swing.JRadioButton jrbtn_no;
    private javax.swing.JRadioButton jrbtn_si;
    private javax.swing.JTextField jtxt_amaterno;
    private javax.swing.JTextField jtxt_apaterno;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_rut_dosPrimeros;
    private javax.swing.JTextField jtxt_rut_dv;
    private javax.swing.JTextField jtxt_snombre;
    private javax.swing.JTextField jtxt_user;
    // End of variables declaration//GEN-END:variables

}
