/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Sesion;
import Controlador.productoCRUD;
import Controlador.ventaCRUD;
import Modelo.Detalle_Venta;
import Modelo.Producto;
import Modelo.Venta;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/**
 *
 * @author esteban
 */
public class FORM_nueva_venta extends javax.swing.JFrame {

    private productoCRUD prodCRUD;
    private ventaCRUD ventCRUD;
    private JTable tablaCarrito;
    private DefaultTableModel modeloCarrito;
    private Map<String, Producto> productoMap; 
    private JLabel labelTotal;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FORM_nueva_venta.class.getName());

    /**
     * Creates new form FORM_nueva_venta
     */
    public FORM_nueva_venta() {
        initComponents();
        this.prodCRUD = new productoCRUD();
        this.ventCRUD = new ventaCRUD();
        this.productoMap = new HashMap<>();
        this.setLocationRelativeTo(null);

        configurarCarrito(); 
        cargarProductosComboBox(); 
    }

    private void configurarCarrito() {
        modeloCarrito = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Cant.", "P. Unitario", "Subtotal"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tablaCarrito = new JTable(modeloCarrito);

        
        JScrollPane scrollPane = new JScrollPane(tablaCarrito);

       
        labelTotal = new JLabel("TOTAL: $0.00");
        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 14));

        jPanel3.setLayout(new BorderLayout());

        jPanel3.add(scrollPane, BorderLayout.CENTER);
        jPanel3.add(labelTotal, BorderLayout.SOUTH);

        jPanel3.revalidate();
        jPanel3.repaint();
    }

    private void actualizarTotal() {
        double total = 0;
        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            total += (double) modeloCarrito.getValueAt(i, 4);
        }
        labelTotal.setText(String.format("TOTAL: $%.2f", total));
    }

    private void cargarProductosComboBox() {
        try {
            jmi_Seleccionar.removeAllItems(); 
            productoMap.clear();

            jmi_Seleccionar.addItem("Seleccione un producto");

            List<Producto> productos = prodCRUD.obtenerProductos();

            for (Producto p : productos) {
   
                String displayText = String.format(
                        "ID: %d - %s (Stock: %d)",
                        p.getId_producto(),
                        p.getNombre(),
                        p.getStock()
                );

                jmi_Seleccionar.addItem(displayText);

                productoMap.put(displayText, p);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage(), "Error de Conexión", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar productos", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbtn_regresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jmi_Seleccionar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtxt_Cantidad = new javax.swing.JTextField();
        jbtn_AgregarCarrito = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtn_generarVenta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Venta");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jbtn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        jbtn_regresar.setText("Volver al Menu");
        jbtn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_regresarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Agregar Producto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Producto");
        jLabel2.setToolTipText("");

        jmi_Seleccionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Item 2", "Item 3", "Item 4" }));
        jmi_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_SeleccionarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad");

        jbtn_AgregarCarrito.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_AgregarCarrito.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_AgregarCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jbtn_AgregarCarrito.setText("Agregar al Carrito ");
        jbtn_AgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AgregarCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmi_Seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtn_AgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmi_Seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jbtn_AgregarCarrito)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jbtn_generarVenta.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_generarVenta.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_generarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jbtn_generarVenta.setText("Generar venta");
        jbtn_generarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_generarVentaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Carrito de compra");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_regresar))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_generarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_generarVenta)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_SeleccionarActionPerformed

    }//GEN-LAST:event_jmi_SeleccionarActionPerformed

    private void jbtn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_regresarActionPerformed
        FORM_menu_principal menu = new FORM_menu_principal();
        menu.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_jbtn_regresarActionPerformed

    private void jbtn_AgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AgregarCarritoActionPerformed
        String itemSeleccionado = (String) jmi_Seleccionar.getSelectedItem();
        if (itemSeleccionado == null || "Seleccione un producto".equals(itemSeleccionado)) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String cantidadStr = jtxt_Cantidad.getText().trim();
        int cantidad;
        try {
            cantidad = Integer.parseInt(cantidadStr);
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser un número positivo.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.", "Error de Formato", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Producto p = productoMap.get(itemSeleccionado);
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Error: Producto no encontrado en el mapa.", "Error Interno", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cantidad > p.getStock()) {
            JOptionPane.showMessageDialog(this, 
                "Stock insuficiente. Solo quedan " + p.getStock() + " unidades de " + p.getNombre(), 
                "Error de Stock", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double subtotal = p.getPrecio_venta() * cantidad; 
        modeloCarrito.addRow(new Object[]{
            p.getId_producto(),
            p.getNombre(),
            cantidad,
            p.getPrecio_venta(),
            subtotal
        });
        
        actualizarTotal();
        
        jtxt_Cantidad.setText("");
        jmi_Seleccionar.setSelectedIndex(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_AgregarCarritoActionPerformed

    private void jbtn_generarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_generarVentaActionPerformed
        int rut = Sesion.getInstancia().getRutUsuario();
        if (modeloCarrito.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío. Agregue productos antes de generar la venta.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Venta venta = new Venta();
        List<Detalle_Venta> detalles = new ArrayList<>();

        double total = Double.parseDouble(labelTotal.getText().replace("TOTAL: $", "").replace(",", "."));
        venta.setRun_vendedor(rut);
        venta.setTotal_Venta((int) total);

        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            Detalle_Venta d = new Detalle_Venta();
            d.setId_producto((Integer) modeloCarrito.getValueAt(i, 0));
            d.setCantidad((Integer) modeloCarrito.getValueAt(i, 2));   
            d.setPrecio_unitario((int) modeloCarrito.getValueAt(i, 3)); 
            detalles.add(d);
        }

        try {
            ventCRUD.crearVenta(venta, detalles);

            JOptionPane.showMessageDialog(this,
                    "Venta N° " + venta.getId_venta() + " registrada con éxito.",
                    "Venta Exitosa",
                    JOptionPane.INFORMATION_MESSAGE);

            modeloCarrito.setRowCount(0);
            actualizarTotal();

            cargarProductosComboBox();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al registrar la venta:\n" + e.getMessage(),
                    "Error de Venta (CRUD)",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error CRUD al generar venta", e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_generarVentaActionPerformed

    /**
     * @param args the command line arguments //
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new FORM_nueva_venta().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtn_AgregarCarrito;
    private javax.swing.JButton jbtn_generarVenta;
    private javax.swing.JButton jbtn_regresar;
    private javax.swing.JComboBox<String> jmi_Seleccionar;
    private javax.swing.JTextField jtxt_Cantidad;
    // End of variables declaration//GEN-END:variables
}
