/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.vendedorCRUD;
import Modelo.Vendedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shazk
 */
public class FORM_actualizarVendedor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FORM_actualizarVendedor.class.getName());

    /**
     * Creates new form FORM_actualizarVendedor
     */
    public FORM_actualizarVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jtbtn_Actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_ActualizarVendedor = new javax.swing.JTable();
        jbtn_volver = new javax.swing.JButton();
        jtbn_elim = new javax.swing.JButton();

        jLabel6.setText("Apellido Materno:");

        jLabel8.setText("Apellido Materno:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbtn_Actualizar.setText("Actualizar");
        jtbtn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn_ActualizarActionPerformed(evt);
            }
        });

        jtbl_ActualizarVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Run_vendedor", "Nombre", "Seguno_Nombre", "Apellido_Paterno", "Apellido_materno", "Username", "administrador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbl_ActualizarVendedor);

        jbtn_volver.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_volver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        jbtn_volver.setText("Volver");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        jtbn_elim.setText("Eliminar");
        jtbn_elim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbn_elimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jtbtn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtbn_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbtn_volver, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbtn_Actualizar)
                    .addComponent(jtbn_elim))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbtn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn_ActualizarActionPerformed
        int run_vendedor = 0;
        String nombre = null;
        String segundo_nombre = null;
        String apellido_paterno = null;
        String apellido_materno = null;
        String username = null;
        String administrador = null;

        vendedorCRUD lista = new vendedorCRUD();
        List<Vendedor> lis = lista.listarVendedores();

        DefaultTableModel tabla = (DefaultTableModel) this.jtbl_ActualizarVendedor.getModel();

        tabla.setRowCount(0);

        for (Vendedor li : lis) {

            run_vendedor = li.getRun_vendedor();
            nombre = li.getNombre_vendedor();
            segundo_nombre = li.getSegundo_nombre_vendedor();
            apellido_paterno = li.getApellidoP_Vendedor();
            apellido_materno = li.getApellidoM_vendedor();
            username = li.getUsername();
            if (li.isEs_admin()) {
                administrador = "Y";

            } else {
                administrador = "N";

            }
            tabla.addRow(new Object[]{run_vendedor, nombre, segundo_nombre, apellido_paterno, apellido_materno, username, administrador});

        }


    }//GEN-LAST:event_jtbtn_ActualizarActionPerformed

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        FORM_admin ad = new FORM_admin();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_volverActionPerformed

    private void jtbn_elimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbn_elimActionPerformed
        vendedorCRUD vendC = new vendedorCRUD();
        int fila = this.jtbl_ActualizarVendedor.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(this,"Debe seleccionar una fila","Actualizar",2);
               
        }
                
        String rut = this.jtbl_ActualizarVendedor.getValueAt(fila, 0).toString();
        int rut1 = Integer.parseInt(rut);
        
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar al vendedor con RUT " + rut1 + "?", "CONFIRMACION", 2);
        if (confirmar == 0) {
            vendC.eliminarVendedor(rut1);
            
        }else{
            JOptionPane.showMessageDialog(this, "Se aborto la eliminacion del vendedor", "MENSAJE", 1);
        }


    }//GEN-LAST:event_jtbn_elimActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new FORM_actualizarVendedor().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JTable jtbl_ActualizarVendedor;
    private javax.swing.JButton jtbn_elim;
    private javax.swing.JButton jtbtn_Actualizar;
    // End of variables declaration//GEN-END:variables
}
